spring:
  application:
    name: authentication-service
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5438/auth_db
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081
