apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8081

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://auth-db:5432/authdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: JWT_SECRET
              value: com-innowise-authentication-service-secret-key

          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 0
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          startupProbe:
            tcpSocket:
              port: 8081
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 5